version: "3.9"

services:
    app:
        container_name: gallery.marktaguiad.dev
        image: ghcr.io/mcbtaguiad/gallery.marktaguiad.dev:main
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:80"
